### ISSUE TITLE
What we have to do

### ISSUE THREAD

**Issue by AhnMo** [saykim0727/IS511#7]
Meeting #2

---
1. Mining code analysis 
- @AhnMo 
- @ssssragon 

2. Statistics
- @20183300 

3. Currently existing block solution + Intro + Abstrct
- @saykim0727

**Comment by saykim0727** [comment]
Meeting #2

---
1. Mining code analysis 
- @AhnMo 

2. Statistics
- @20183300 

3. Currently existing block solution + Intro + Abstrct
- @saykim0727 

4. Search papers
- @ssssragon
